AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates a least-privilege deployment role that explicitly trusts the central tooling role ARN.

Parameters:
  ArtifactS3BucketName:
    Type: String
    Description: "The name of the S3 bucket where the Lambda deployment package is stored."
  ProjectName:
    Type: String
    Description: "The base name for created resources (must match the 'Name' parameter of the application stack)."
    Default: "AutomatedCloudWatch"
  TargetRoleName:
    Type: String
    Default: "InternalToolingDeploymentRole"
  ToolingRoleArn:
    Type: String
    Description: "The full ARN of the central CI/CD tooling role that is allowed to assume this role."

Resources:
  InternalToolingDeploymentRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref TargetRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ToolingRoleArn
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "CloudWatchDashboardDeployerPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::${ArtifactS3BucketName}/*"
              - Effect: Allow
                Action:
                  - "iam:GetRole"
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:PutRolePolicy"
                  - "iam:DeleteRolePolicy"
                  - "iam:PassRole"
                Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-*"
                Condition:
                  StringEquals:
                    "iam:PassedToService": "lambda.amazonaws.com"
              - Effect: Allow
                Action:
                  - "lambda:GetFunction"
                  - "lambda:CreateFunction"
                  - "lambda:DeleteFunction"
                  - "lambda:UpdateFunctionCode"
                  - "lambda:UpdateFunctionConfiguration"
                  - "lambda:AddPermission"
                  - "lambda:RemovePermission"
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function/${ProjectName}-*"
              - Effect: Allow
                Action:
                  - "events:PutRule"
                  - "events:DeleteRule"
                  - "events:DescribeRule"
                  - "events:PutTargets"
                  - "events:RemoveTargets"
                Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/${ProjectName}-*"
              - Effect: Allow
                Action:
                  - "cloudwatch:PutDashboard"
                  - "cloudwatch:GetDashboard"
                Resource: !Sub "arn:aws:cloudwatch::${AWS::AccountId}:dashboard/${ProjectName}-*"
