name: OIDC Debugger V2

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug-oidc-claims:
    name: "Debug OIDC Claims"
    runs-on: ubuntu-latest
    steps:
      - name: Enable Full AWS SDK Debugging
        run: echo "AWS_SDK_LOAD_CONFIG=true" >> $GITHUB_ENV

      - name: Assume Role with OIDC (Debug Mode)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # This role ARN can be any valid role ARN from your account.
          # It doesn't matter if it fails, we just want to see the debug logs.
          role-to-assume: ${{ secrets.MANAGEMENT_CONNECTOR_ROLE_ARN }}
          aws-region: "us-east-1"
          # This enables verbose logging from the AWS SDK.
          log-level: "debug"
